# Generated by Django 3.2 on 2022-05-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productemail',
            unique_together={('product_id', 'email', 'date_deleted')},
        ),
    ]
